### ISSUE TITLE
Sensors not showing

### ISSUE THREAD

**Issue by partach** [ticapix/home-assistant_sdm630#3]
Hi,

I have followed the steps and don't see the sensors show up in home assistant.
Made a small python script to check serial and connection and that is working.
My config:
```
modbus:
 - type: serial
   baudrate: 9600
   bytesize: 8
   method: rtu
   parity: N
   port: /dev/serial0
   stopbits: 1
   close_comm_on_error: false
   retry_on_empty: true
   retries: 10
   delay: 10
   message_wait_milliseconds: 1000
   timeout: 10
# Sensors
sensor:
 - platform: modbus
   registers: !include sdm630_registers.yaml
```
The logs of HA is also not showing any problem.
Can't figure out what the problem is. Even rebooted the PI to see if that would help.
No matter what i do, the sensors are not visible in HA (nor any modbus device).
Pls help.
